# build.yml
---
name: build

on:
  workflow_call:
    inputs:
      version_override:
        type: string
        description: "Version number override"
        required: false

jobs:
  windows:
    strategy:
      matrix:
        architecture: [x64, x86]  
    uses: ./.github/workflows/build-windows.yml
    with:
      version_override: ${{ inputs.version_override }}
      architecture: ${{ matrix.architecture }}

  linux:
    strategy:
      matrix:
        architecture: [x64, arm64]
    uses: ./.github/workflows/build-linux.yml
    with:
      version_override: ${{ inputs.version_override }}
      runs_on: ubuntu-latest
      architecture: ${{ matrix.architecture }}
